name: Compile Infinity-X 3.10 Android 16

on:
  workflow_dispatch: # This adds the manual "Run workflow" button

jobs:
  build_job:
    runs-on: ubuntu-22.04

    steps:
    - name: Get source from repository
      uses: actions/checkout@v4

    - name: Clean up the server space
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo apt-get update && sudo apt-get install -y curl

    - name: Run Build Core Process
      run: |
        # This copies your munch.xml from your repo to the build folder safely
        cp munch.xml /tmp/munch.xml
        chmod +x build.sh
        bash build.sh

    - name: Save My Finished ROM File
      uses: actions/upload-artifact@v4
      with:
        name: POCO-F4-Infinity-16-Zip
        path: ~/android/out/target/product/munch/Project_Infinity-X-*.zip
